### ISSUE TITLE
Hypotheses.org - Mettre une page dans un menu deroulant

### ISSUE THREAD

**Issue by zoometh** [CAA-France/website#1]
J'ai cree cette web page: https://caafrance.hypotheses.org/autres-chapitres-nationaux-du-caa

Une carte interactive des chapitres du CAA hebergee sur  GitHub https://CAA-France.github.io/website/maps/caa-national-chapter.html

---

Comment faire dans Hypothese.org pour la faire figurer dans le panneau "Presentation CAA-FR", apres "A propos de ce site"?

![image](https://github.com/user-attachments/assets/b8ea593a-5d5b-48b5-9b13-27f42ec54169)

**Comment by sebastien-plutniak** [comment]
Merci Thomas !
pour éditer le menu, ça se passe dans Apparence / Menu
ici : https://caafrance.hypotheses.org/wp-admin/nav-menus.php
